name: gym_tracker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  go_router: ^10.1.2
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  provider: ^6.0.5
  responsive_sizer: ^3.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
